
-------------------------------------------------------------------------------
-- Schema: tabelas para Currículo (tbl_cco_user) e Coleções (tbl_ccos)
-- Oracle Database 12c+ (usa GENERATED AS IDENTITY para IDs)
-------------------------------------------------------------------------------

-- 1) Tabela de coleções (tabela pai)
CREATE TABLE tbl_ccos (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_set_name VARCHAR2(200)       NOT NULL,
    total_cco_collection NUMBER             DEFAULT 0 NOT NULL,
    CONSTRAINT uq_tbl_ccos_name UNIQUE (collection_set_name),
    CONSTRAINT chk_tbl_ccos_total_nonneg CHECK (total_cco_collection >= 0)
);

COMMENT ON TABLE tbl_ccos IS 'Coleções de currículos (sets)';
COMMENT ON COLUMN tbl_ccos.id IS 'Identificador único da coleção';
COMMENT ON COLUMN tbl_ccos.collection_set_name IS 'Nome do conjunto/coleção';
COMMENT ON COLUMN tbl_ccos.total_cco_collection IS 'Total de currículos associados (informativo)';

-- Índice extra opcional (dependendo do volume de buscas por nome)
CREATE INDEX idx_tbl_ccos_name ON tbl_ccos (collection_set_name);


-- 2) Tabela de usuário/currículo (tabela filha)
CREATE TABLE tbl_cco_user (
    id                   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                 VARCHAR2(200)      NOT NULL,
    sobre_mim            CLOB,
    experiencia          CLOB,
    habilidades          CLOB,
    idiomas              VARCHAR2(400),
    contato              VARCHAR2(400),
    formacao             CLOB,
    idcollectioncco      NUMBER,  -- FK para tbl_ccos.id

    CONSTRAINT fk_tbl_cco_user_ccos
        FOREIGN KEY (idcollectioncco)
        REFERENCES tbl_ccos (id)
        ON DELETE SET NULL
);

COMMENT ON TABLE tbl_cco_user IS 'Tabela de currículos dos usuários';
COMMENT ON COLUMN tbl_cco_user.id IS 'Identificador único do currículo';
COMMENT ON COLUMN tbl_cco_user.nome IS 'Nome completo';
COMMENT ON COLUMN tbl_cco_user.sobre_mim IS 'Resumo / Sobre mim';
COMMENT ON COLUMN tbl_cco_user.experiencia IS 'Experiências profissionais';
COMMENT ON COLUMN tbl_cco_user.habilidades IS 'Habilidades principais';
COMMENT ON COLUMN tbl_cco_user.idiomas IS 'Idiomas (ex.: pt-BR, en-US)';
COMMENT ON COLUMN tbl_cco_user.contato IS 'Contato: e-mail/telefone/LinkedIn';
COMMENT ON COLUMN tbl_cco_user.formacao IS 'Formação acadêmica';
COMMENT ON COLUMN tbl_cco_user.idcollectioncco IS 'FK para a coleção (tbl_ccos.id)';

-- Índices úteis
CREATE INDEX idx_tbl_cco_user_nome ON tbl_cco_user (nome);
CREATE INDEX idx_tbl_cco_user_idcollectioncco ON tbl_cco_user (idcollectioncco);


